### PR TITLE
Delete recipes that are better-served by homebrew

### PR DESCRIPTION
**Pull request by wendorf**
There are a lot of recipes that are manually downloading/installing applications that are now available via homebrew.

- alfred 2.6 has built-in support for cask
- Available in caskroom/cask:
  - Google Voice and Video (as google-hangouts)
  - Kaleidoscope
  - pg_admin (as pgadmin3)
  - ShiftIt (without auto-startup)
  - MacVim (also available in homebrew)
- Available in caskroom/versions:
  - google-chrome-canary
  - Firefox Aurora (as firefoxdeveloperedition)

### CODE REVIEW

**Comment by wendorf** [comment]
Just noticed: The version of ShiftIt that we were previously installing was from [onsi/ShiftIt](https://github.com/onsi/ShiftIt), but the cask installs [fikovnik/ShiftIt](https://github.com/fikovnik/ShiftIt). That repo is under much more active development, but likely has some noticeable differences.

**Comment by wendorf** [comment]
Updated PR to not remove ShiftIt, since it's less of a no-brainer.

**Comment by funcode** [comment]
So we should remove lines like "sprout-osx-apps::flycut" from our own soloistrc, right?
Then how could we get flycut installed automatically?

**Comment by wendorf** [comment]
Hi @funcode,

You don't need to remove those lines until you have updated your Cheffile.lock to point to the latest version of the sprout-osx-apps cookbook. Once you do that, however, you will need to switch to installing those recipes via homebrew.

You can look at the [sprout-wrap example soloistrc file](https://github.com/pivotal-sprout/sprout-wrap/blob/d8eac99441ad2ac52421901bdfa895ea82fdae2c/soloistrc#L66-L97) to see an example of how to configure sprout-wrap to install recipes via homebrew. Just make sure you are running the [sprout-base::homebrew and sprout-homebrew](https://github.com/pivotal-sprout/sprout-wrap/blob/d8eac99441ad2ac52421901bdfa895ea82fdae2c/soloistrc#L6-L7) recipes, and your list of recipes/casks will install.

**Pull request merged**
